### ISSUE TITLE
Add TcpListenerOption support to K8S Gateway API implementation

### ISSUE THREAD

**Issue by DuncanDoyle** [k8sgateway/k8sgateway#10361]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.18.0-rc1

**Comment by DuncanDoyle** [comment]
Note that in KGateway, we can send `localRateLimit` via `TrafficPolicy` on both `Gateway` and `HTTPRoute`:

```
apiVersion: gateway.kgateway.dev/v1alpha1	
kind: TrafficPolicy
metadata:
  name: lrl-traffic-policy-gateway
  namespace: ingress-gw
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gw
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 1
        tokensPerFill: 1
        fillInterval: 100s
```

```
apiVersion: gateway.kgateway.dev/v1alpha1	
kind: TrafficPolicy
metadata:
  name: lrl-traffic-policy
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api-example-com
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 1
        tokensPerFill: 1
        fillInterval: 100s
```

Do we have settings for `connectionLimit` and `tcpProxySettings` as well in KGateway `TrafficPolicy`.

Once we rebase on KGateway, do we still want to add these features in a GE *Options type fashion, or do we ask customers to configure these features via `TrafficPolicy`, and thus asking them to mix API styles?
