### ISSUE TITLE
HTTPRoute delegation does not work when multiple HTTPRoutes delegate to the same HTTPRoute

### ISSUE THREAD

**Issue by DuncanDoyle** [k8sgateway/k8sgateway#10379]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.18.0-beta2

### Kubernetes Version

1.28.11

### Describe the bug

When you have a single root `HTTPRoute` that delegates to  2 APIProduct `HTTPRoutes` that both delegate to the same `HTTPRoute`, only one of the routes API routes will work.

E.g. given the following configuration:
```
            /---> APIProduct-1 Route --\
Root-Route |                            ---> Service Route ---> Service
            \---> APIProduct-2 Route --/
```

Only one of the APIProduct routes will work. The other route will return a 404 when trying to access it.

### Expected Behavior

Multiple `HTTPRoutes` should be able to delegate to the same `HTTPRoute`.

### Steps to reproduce the bug

Reproducer project here: https://github.com/DuncanDoyle/gg-httproute-delegation-reproducer

Instructions in Readme.

**Comment by shashankram** [comment]
We have a test that validates multiple parents with a delegation depth of 2 (parent1->child, parent2->child): https://github.com/solo-io/gloo/blob/main/projects/gateway2/translator/testutils/inputs/delegation/multiple_parents.yaml

It seems multi-level delegation with depth > 2 (r1->r2->r3) isn't working as expected.

@DuncanDoyle could you share the status on the routes, and if you see any error logs in the controller?

**Comment by DuncanDoyle** [comment]
No errors in the Gloo controller logs AFAICT. See status of the routes below.

Root route:
```
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-11-25T16:38:14Z"
      message: ""
      observedGeneration: 2
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-11-25T16:38:14Z"
      message: ""
      observedGeneration: 2
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: solo.io/gloo-gateway
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: gw
      namespace: ingress-gw
```

APIProduct 1 Route:
```
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-11-25T16:48:20Z"
      message: ""
      observedGeneration: 10
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-11-25T16:48:20Z"
      message: ""
      observedGeneration: 10
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: solo.io/gloo-gateway
    parentRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: api-example-com
      namespace: default
```

APIProduct 2 Route:
```
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-11-25T18:33:05Z"
      message: 'ignoring child route default/apiproduct-2 for parent default/httpbin:
        cyclic reference detected while evaluating delegated routes'
      observedGeneration: 2
      reason: RefNotPermitted
      status: "False"
      type: ResolvedRefs
    - lastTransitionTime: "2024-11-25T16:48:20Z"
      message: ""
      observedGeneration: 2
      reason: Accepted
      status: "True"
      type: Accepted
    controllerName: solo.io/gloo-gateway
    parentRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: api-example-com
      namespace: default
```

Service HTTPRoute:
```
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-11-25T18:33:05Z"
      message: ""
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-11-25T18:33:05Z"
      message: ""
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: solo.io/gloo-gateway
    parentRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: apiproduct-1
      namespace: default
```
