### ISSUE TITLE
[helm] disabling default gateway-proxy prevents proxy deployments for other data-planes being created

### ISSUE THREAD

**Issue by lgadban** [k8sgateway/k8sgateway#4956]
**Describe the bug**
When using helm to create additional data-planes/proxies if you disable the default gateway-proxy, the proxy deployment for the additional data-planes will not be created.

**To Reproduce**
Install with these overrides:
```
global:
  extensions:
    dataplanePerProxy: true
gloo:
  gatewayProxies:
    gatewayProxy:
      disabled: true
    internalProxy:
      gatewaySettings:
        customHttpGateway:
          options:
            extauth:
              extauthzServerRef:
                name: extauth-internal-proxy
                namespace: gloo-system
            ratelimitServer:
              ratelimitServerRef:
                name: rate-limit-internal-proxy
                namespace: gloo-system
          virtualServiceSelector:
            gateway-type: internal
```

See the following deployments:
```
% kubectl get deploy -n gloo-system | grep internal-proxy
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
extauth-internal-proxy      1/1     1            1           78s
rate-limit-internal-proxy   1/1     1            1           78s
redis-internal-proxy        1/1     1            1           78s
```

**Expected behavior**
The actual proxy should be deployed, e.g. `internal-proxy`

**Additional context**
```
]% glooctl version
Client: {"version":"1.7.8"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.8.0","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.8.0","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.8.0","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.8.0","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```

This is another bug related to multiple data planes via helm:
https://github.com/solo-io/gloo/issues/4696
