### ISSUE TITLE
can't start the Gateway pod with automountServiceAccountToken: false

### ISSUE THREAD

**Issue by bcollard** [k8sgateway/k8sgateway#4958]
**Describe the bug**
The Gateway pod won't start if its Service Account has this `automountServiceAccountToken: false` option

Helm values:
```yaml
gloo:
  gateway:
    serviceAccount:
      disableAutomount: true
```

Pod logs:
```
"Thu, 01 Jul 2021 13:49:43 UTC: /workspace/gloo/projects/gateway/cmd/main.go:12"	err in main: "invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"
```

-> does it make sense to have this option?
