### ISSUE TITLE
dynamic routing with subset selectors

### ISSUE THREAD

**Issue by bcollard** [k8sgateway/k8sgateway#4959]
The goal is to use dynamic values in [subset](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/subsets/) selectors
For example, a header may contain the label's key/value that will be used to route the request to a given pods subset

**Comment by jannes** [comment]
in terms of declaring this, a subsetHeaders field could be added to the subset field. e.g:
```
routes:
  - matchers:
    - headers:
      - name: subset-selector
      prefix: /example
    name: subset-route-dynamic
    routeAction:
      single:
        subset:
          subsetHeaders:
            - subset-selector
        upstream:
          name: example-upstream
          namespace: gloo-system
```
