### ISSUE TITLE
make 'glooctl check' report a warning when a listener is in draining mode

### ISSUE THREAD

**Issue by bcollard** [k8sgateway/k8sgateway#4968]
**Is your feature request related to a problem? Please describe.**
There are some configuration changes at the GW level that will set the [Listener](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/lds) in a draining mode.

Example:
```yaml
kubectl -n gloo-system patch --type merge gw/gateway-proxy -p "
spec:
  options:
    perConnectionBufferLimitBytes: 5000000 # 5 MB
"
``` 

After such a change, the listener must be updated, so it will enter in draining mode for, b[y default,](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-drain-time-s) 10min (600s).
This is a really long period, that is not perceived by the administrator. Because connections keep being accepted but the new listener config is not yet active.

**Describe the solution you'd like**
`glooctl check` should report some warning when a listener in a draining mode

**Describe alternatives you've considered**
Adding a new graph in Grafana based on the metric `listener_manager.total_listeners_draining`

**Additional context**
Gloo Edge v1.8
