### ISSUE TITLE
WAF `customSettingsFile` should accept an array of files

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#4972]
**Is your feature request related to a problem? Please describe.**

Right now WAF can only accept a single file for `customSettingsFile` but a customer has expressed interest in mounting and applying several rule files without the need to combine them all into one giant rules.conf file.

**Describe the solution you'd like**

```
#Current
      waf:
        coreRuleSet:
          customSettingsFile: "/rules/rules.conf"
```

```
#Proposed
      waf:
        coreRuleSet:
          customSettingsFiles: 
          - file: "/rules/rules1.conf"
          - file: "/rules/rules2.conf"
```

**Describe alternatives you've considered**

Combine all rules into a single mega rule.conf

**Additional context**

glooe v1.8.0
