### ISSUE TITLE
Enterprise helm chart produces duplicate `restartPolicy` in gateway-certgen Job spec

### ISSUE THREAD

**Issue by jameshbarton** [k8sgateway/k8sgateway#5021]
**Describe the bug**
The Gloo Edge Enterprise helm chart produces duplicate `restartPolicy` in gateway-certgen Job spec.

**To Reproduce**
1. Generate helm template with `gateway.certGenJob.restartPolicy=OnFailure` value.
```
helm template gloo-ee --version v1.8.0  glooe/gloo-ee --namespace gloo-system --set-string license_key=$GLOO_KEY --set gateway.certGenJob.restartPolicy=OnFailure
```
2. Observe the invalid duplicate `restartPolicy` attribute in the gateway-certgen Job spec.
```
# Source: gloo-ee/charts/gloo/templates/6.5-gateway-certgen-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: gateway-certgen
  name: gateway-certgen
  namespace: gloo-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        gloo: gateway-certgen
    spec:
      serviceAccountName: certgen
      restartPolicy: OnFailure
      containers:
        - image: quay.io/solo-io/certgen:1.8.0
          imagePullPolicy: IfNotPresent
          name: certgen
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:

            - "--secret-name=gateway-validation-certs"
            - "--svc-name=gateway"
            - "--validating-webhook-configuration-name=gloo-gateway-validation-webhook-gloo-system"
      restartPolicy: OnFailure
  # this feature is still in Alpha, which means it must be manually enabled in the k8s api server
  # with --feature-gates="TTLAfterFinished=true". This flag also works with minikube start ...
  # if the feature flag is not enabled in the k8s api server, this setting will be silently ignored at creation time
  ttlSecondsAfterFinished: 60
```

**Expected behavior**
Generate a single `restartPolicy` attribute.

**Additional context**
- Gloo Edge Enterprise version 1.8.0
- Internal Reference: https://solo-io.slack.com/archives/G01C1S1MJN4/p1626264848002000
