### ISSUE TITLE
convertGrpcStatus does not add grpc-status or grpc-message headers

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#5039]
**Describe the bug**
setting convertGrpcStatus in https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc_json/grpc_json.proto.sk/ does not add grpc-status or grpc-message headers when an error occurs. Also no error details were added the to body as json.

**To Reproduce**
1. Follow advanced guide (https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest_advanced/)
2. Add the following to the gateway 
```yml
...
 httpGateway:
    options:
      grpcJsonTranscoder:
        convertGrpcStatus: true
        printOptions:
          alwaysPrintPrimitiveFields: true
          preserveProtoFieldNames: true
...
```
3. Using grpcurl send a bad request (grpcurl -v --plaintext -d '{"theme": "music"}' $URL:80 main.Bookstore.CreateShelf
```sh
Resolved method descriptor:
rpc CreateShelf ( .main.CreateShelfRequest ) returns ( .main.Shelf ) {
  option (.google.api.http) = { post:"/shelf" body:"shelf"  };
}

Request metadata to send:
(empty)
Error invoking method "main.Bookstore.CreateShelf": error getting request data: message type main.CreateShelfRequest has no known field named theme
```

**Expected behavior**
grpc-status and grpc-message headers should be returned

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version - v1.8.0
- Kubernetes version - 1.20
