### ISSUE TITLE
Certificates mounted with sslFiles do not reload on renewal (cert-manager)

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#5040]
**Describe the bug**
Certificates mounted with sslFiles do not reload on renewal (cert-manager)

**To Reproduce**
1. Follow TLS docs, but use sslFiles instead of sslConfig (https://docs.solo.io/gloo-edge/latest/guides/security/tls/server_tls/)

```
#values.yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      extraVolumes:
        - name: tls-crt
          secret:
            secretName: gloo-cert
            items:
              - key: tls.crt
                path: "tls.crt"
        - name: tls-key
          secret:
            secretName: gloo-cert
            items:
              - key: tls.key
                path: "tls.key"
      extraProxyVolumeMounts:
        - name: tls-crt
          mountPath: "/certs/crt"
          readOnly: true
        - name: tls-key
          mountPath: "/certs/key"
          readOnly: true
```

```
#vs.yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: my-vs
  namespace: gloo-system
spec:
  sslConfig:
    sslFiles:
      tlsCert: "/certs/crt/tls.crt"
      tlsKey: "/certs/key/tls.key"
  virtualHost:
    domains:
      - "*"  
    routes:
      - matchers:
        - prefix: /
        options:
          extauth:
            disable: true
        delegateAction:
          ref:
            name: "my-rt"
            namespace: "gloo-system"
```
2. Make a change to the cert secret. 
3. New cert will not be loaded.

**Expected behavior**
Certificates mounted with sslFiles and extra proxy volumes should be loaded/served on renewal

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version - v1.8.0
- Kubernetes version - 1.20
