### ISSUE TITLE
`gatewayProxies.NAME.readConfig=true` can drastically increase cpu usage on larger deployments

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#5057]
**Describe the bug**
`gatewayProxies.NAME.readConfig=true` can drastically increase cpu usage on larger deployments

**To Reproduce**
```
helm install gloo glooe/gloo-ee --namespace gloo-system \
  --create-namespace --set-string license_key=$KEY --values ./test-values.yaml --version v1.8.0

#test-values.yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          replicas: 2
      readConfig: false
```
Verify CPU

```
helm upgrade gloo glooe/gloo-ee --namespace gloo-system \
  --create-namespace --set-string license_key=$KEY--values ./test-values.yaml --version v1.8.0

#test-values.yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          replicas: 2
      readConfig: true
```
Verify CPU has increased.

Small Config:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/65769106/126392346-228ce7db-3ad8-48c3-8d43-f810f8b62a56.png">

Larger Config:
![image](https://user-images.githubusercontent.com/65769106/126392469-3d567ecf-c3eb-4c2a-860f-0862d3ba34c9.png)

**Expected behavior**
Little to no cpu usage increase

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version - v1.8.0
- Kubernetes version - 1.20
