### ISSUE TITLE
proxy name leads to wrong helm interpolation

### ISSUE THREAD

**Issue by antonioberben** [k8sgateway/k8sgateway#5072]
When you use following custom values for your installation (tested in versions `1.8.0` and `1.8.1`), you get 2 configmaps with name `gateway-proxy-envoy-config`

custom-values:
```
gloo:
  gatewayProxies:
    gateway-proxy:
      service:
        extraAnnotations:
          "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
license_key: XXXXX
```

## How to reproduce:

```
helm template gloo glooe/gloo-ee --version 1.8.0  -f <custom values from above>  --output-dir out
```
File:
```
out/gloo-ee/charts/gloo/templates/9-gateway-proxy-configmap.yaml
```

You will see two configmaps.

The reason is that the chart notice a new name in the `proxyGateway` called ` gateway-proxy` (notice the `-`). And it is different that the default one coming from the default `values.yaml` called `gatewayProxy`. Therefore, two confimap are generated.

But the name convention in the generated resources (dash case) makes that both resource have the very same name: `gateway-proxy-envoy-config`, driving to a falling installation.

## Proposed solution

Enforce to avoid dash-case for names.

## Update

The issue shows up when we followed the documentation and replace the placeholder `NAME` with a name we took the name of the generated proxy `gateway-proxy`.

It would be interesting to warn about this somehow or, as mentioned before, to avoid the conflicting name at the helm chart code.

![image](https://user-images.githubusercontent.com/5262332/127159983-e8b67d75-715c-4693-a514-b0238bef7924.png)

Thank you
