### ISSUE TITLE
gloo gateway stuck on error state when removing the virtual service secret

### ISSUE THREAD

**Issue by DoroNahari** [k8sgateway/k8sgateway#5079]
**Describe the bug**
gloo gateway stuck on error state when removing the virtual service secret

**To Reproduce**
1. `glooctl create secret tls --name upstream-tls --certchain tls.crt --privatekey tls.key`
2. `kubectl apply -f` to the following virtual service (taken from [gloo docs](https://docs.solo.io/gloo-edge/latest/guides/security/tls/server_tls/#serving-certificates-for-multiple-virtual-hosts-with-sni))
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: animal
  namespace: gloo-system
spec:
  displayName: animal
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
    sniDomains:
    - animalstore.example.com
  virtualHost:
    domains:
    - animalstore.example.com
    routes:
    - matchers:
      - exact: /animals
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```
3. Remove the secret with `kubectl delete secrets -n gloo-system upstream-tls`
4. Run `kubectl get gateways -n gloo-system gateway-proxy-ssl -o yaml`
5. See the error (as expected): `Error: SSLConfigError. Reason: SSL secret not found: list did not find secret gloo-system.upstream-tls1\n\t*`
6. Remove the virtual service: `kubectl delete virtualservice -n gloo-system animal`
7. Repeat steps 4-5 and see that the error persist.
8. Apply new virtual service, Repeat step 4 and see that the error disappeared.

**Expected behavior**
After removing a virtual service that was without secret (after step 6) the error in the gateway-proxy-ssl should be removed.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.6.8 and 1.8.0
- Kubernetes version 1.20.8
