### ISSUE TITLE
datadog tracing tags picked from env vars are not added to extauth requests

### ISSUE THREAD

**Issue by bcollard** [k8sgateway/k8sgateway#5208]
**Describe the bug**
Datadog tracing with:

```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      tracing:
        provider:
          environmentVariablesForTags:
            - tag: version
              name: DD_VERSION # this variable isn't setup anywhere - we use the defaultValue
              defaultValue: "1.8.0"
```
The `version` tag is not reported in the traces received by Datadog:

![image](https://user-images.githubusercontent.com/9626829/130265291-5e4cd70c-01fc-43e5-a0ef-cc2be7d5d2c8.png)

This works for tags added to upstream clusters. But not on extauth calls.

**Additional context**
- Gloo Edge version 1.8.5
