### ISSUE TITLE
Transformations should support referencing all headers even if they share the same key

### ISSUE THREAD

**Issue by kdorosh** [k8sgateway/k8sgateway#5326]
**Is your feature request related to a problem? Please describe.**
Transformations can be a bit limiting in that we always take the [first match](https://github.com/solo-io/envoy-gloo/blob/master/source/extensions/filters/http/transformation/inja_transformer.cc#L137) in a header extractor.

This prevents us from doing this like:
```
        responseTransformation:
          transformationTemplate:
            headers:
              "Set-Cookie":
                text: '{{ header("Set-Cookie") }}; SameSite=None'
```
if we say have more than one header (e.g. extauth OIDC with ID and access token cookies).

**Describe the solution you'd like**
We should be able to apply a transformation to every header with a specific key/value, according to the input. A new feature flag for "deep" transformations.

**Describe alternatives you've considered**
Just doing a quick feature request for samesite config, just like we did with secure cookies. This transformation ask is more flexible.

**Additional context**
Extauth test that displays how the OIDC cookies in question look today: https://github.com/solo-io/ext-auth-service/blob/4ecd996b36285490541c81a8bbead2a8732340e4/pkg/config/oidc/oidc_test.go#L338-L353
