### ISSUE TITLE
Clarify the default behaviour of gloo regarding invalid routes

### ISSUE THREAD

**Issue by jmunozro** [k8sgateway/k8sgateway#5332]
**Describe the requested changes**
_When a Virtual Service (or one of its delegated route tables) contains invalid configuration, its routes will no longer be propagated to the Proxy . Instead, the last valid configuration for that Virtual Service will be used._

This information is confusing, when a VS or a delegated rute contains invalid configuration, all changes in all routes, even if they belong to other, not-related, VS are affected. Regarding snapshots, It is an all-or-nothing model, so a single mistake will stop new updates ------> **for the domain** <-------.

**Link to any relevant existing docs**
https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/invalid_route_replacement/

**Additional context**
Internal conversation with @kevin-shelaga and @kdorosh

**Comment by jmunozro** [comment]
To reproduce:
1. install gloo with invalid routes active
2. apply invalid config
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs-team3-broken
spec:
  virtualHost:
    domains:
    - team3.jesus.com
    routes:
      - matchers:
          - prefix: /bad-route
        routeAction:
          single:
            # this destination does not exist
            kube:
              ref:
                name: does-not-exist
                namespace: anywhere
              port: 1234
        options:
          prefixRewrite: /get
```

Apply valid config, it should be accepted but it is not
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs-team3-valid
spec:
  virtualHost:
    domains:
    - team3.jesus.com
    routes:
      - matchers:
          - prefix: /good-route
        routeAction:
          single:
            upstream:
              name: default-httpbin-8000
              namespace: gloo-system
        options:
          prefixRewrite: /get
```

```
$curl $(glooctl proxy url)/bad-route -H 'Host: team3.jesus.com' -i
HTTP/1.1 404 Not Found
date: Wed, 09 Feb 2022 11:35:49 GMT
server: envoy
content-length: 0

$curl $(glooctl proxy url)/good-route -H 'Host: team3.jesus.com' -i
HTTP/1.1 404 Not Found
date: Wed, 09 Feb 2022 11:35:55 GMT
server: envoy
content-length: 0

```
