### ISSUE TITLE
Add example of RateLimitConfig with headers

### ISSUE THREAD

**Issue by antonioberben** [k8sgateway/k8sgateway#5341]
In the documentation, we have an example for `counter`.

https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/crds/#ratelimitconfig-resources

it would very very interesting to have an example with headers because it is a use-case many users go through.

For example:
```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: my-rate-limit-policy
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: id
      rateLimit:
        requestsPerUnit: 1
        unit: HOUR
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: id
          headerName: <my-header-name>
```
