### ISSUE TITLE
Add route to admin port /stats to static_resource listener config for Datadog integration

### ISSUE THREAD

**Issue by sleerssen** [k8sgateway/k8sgateway#5342]
Datadog has an envoy integration that reads the /stats endpoint instead of the prometheus /stats/prometheus endpoint, which is exposed on port 8081 with a route to the admin port.  It would be handy if this was either added to the current default set of prometheus routes or a new listener config added to access /stats.  Alternatively, some method of updating the helm provided template could be used, although it seems just exposing /stats is probably sufficient and keeps the rest of the admin port endpoints secured on localhost.

I've added this locally to my `gateway-proxy-envoy-config`:
```
                            - match:
                                prefix: "/stats"
                                headers:
                                - name: ":method"
                                  exact_match: GET
                              route:
                                prefix_rewrite: /stats
                                cluster: admin_port_cluster
```
