### ISSUE TITLE
Gloo Fed rejects wildcard for CRDs that are not RBAC

### ISSUE THREAD

**Issue by willowmck** [k8sgateway/k8sgateway#5378]
**Describe the bug**
When creating a federated resource, the wildcard '*' annotation for clusters results in the following error: "Cluster * is not registered"

**To Reproduce**
Apply a resource like the following:
```
apiVersion: fed.gateway.solo.io/v1
kind: FederatedVirtualService
metadata:
  name: http-127.0.0.1.nip.io
  namespace: gloo-system
spec:
  placement:
    clusters:
    - '*'
    namespaces:
    - gloo-system
  template:
    metadata:
      name: http-127.0.0.1.nip.io
    spec:
      virtualHost:
        domains:
        - 127.0.0.1.nip.io:*
        routes:
        - delegateAction:
            ref:
              name: http-127.0.0.1.nip.io-a
              namespace: tenant1
          matchers:
          - prefix: /a
```

**Expected behavior**
Gloo should accept this wildcard as referring to all registered clusters.

**Additional context**
Gloo Edge 1.8.13
