### ISSUE TITLE
Default gatewayProxy inherits extraAnnotations from additional gatewayProxy Resources

### ISSUE THREAD

**Issue by ben-taussig-solo** [k8sgateway/k8sgateway#5396]
# Description
As discussed in @kdorosh's comment on #4953, that PR only partially resolved the issue
>  as discussed offline, I think [defaulting to deep map merges when in some cases this can cause incorrect behavior] is a symptom of perhaps a larger problem in our chart

```
gloo:
  gatewayProxies:
    gateway-proxy-internal:
      service:
        extraAnnotations:
          a: value_a
          b: value_b
          c: value_c
    gatewayProxy:
      service:
        extraAnnotations:
          a: value_a
          b: value_b_2
```
The default gateway proxy (`gatewayProxy`) after templating ends up having:
```yaml
a: value_a
b: value_b_2
c: value_c
```
As you can see, the default gateway proxy inherits the annotation `c: value_c` from `gateway-proxy-internal`.

One proposition for resolving this issue has been to relocate inherited annotations under a different attribute, I.E.,:
```yaml
service:
  extraAnnotations:
    a: value_a
    b: value_b_2
  defaultAnnotations:
    c: value_c
```

# Context
Issue https://github.com/solo-io/gloo/issues/4914 and Gloo PR https://github.com/solo-io/gloo/pull/4953 which resolved it
