### ISSUE TITLE
Gateway pod unable to start with malformed RouteTable

### ISSUE THREAD

**Issue by lgadban** [k8sgateway/k8sgateway#5430]
**Describe the bug**
If a malformed `RouteTable` is persisted in config store, the `gateway` container breaks

**To Reproduce**
1. Install GlooE 1.7.19 **without** validating webhook
2. Create following VS and RouteTable (incorrect `options` field): 
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      delegateAction:
        ref:
          name: petstore-routes
          namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - prefix: /
      options:
        hostRewrite: test
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system
```
3. Bounce the `gateway` pod
4. See following error:
```
{"level":"fatal","ts":1633360153.6457982,"logger":"gateway","caller":"setuputils/main_setup.go:88","msg":"error in setup: starting snapshot watch: initial RouteTable list: converting output crd: reading crd spec on resource petstore-routes in namespace gloo-system into v1RouteTable: unknown field \"options\" in matchers.core.gloo.solo.io.Matcher","version":"1.7.22","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:88\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

**Expected behavior**
The control plane should not crash from unknown fields

**Additional context**
- GlooE 1.7.19
- In 1.8.x+ we should be safe from this due to CRD schema validation, but this still is a gap in the control plane's robustness
- Relevant when upgrading from 1.6.x -> 1.7.x
