### ISSUE TITLE
503 errors with UH flags after rolling update of the Kubernetes nodes

### ISSUE THREAD

**Issue by djannot** [k8sgateway/k8sgateway#5449]
**Describe the bug**
The rolling update has been performed to change the ami image of the nodes and there have been no issues during the update.
The Kubernetes nodes where the `gateway-proxy` Pods are running have been upgraded first.

After the end of the operation, everything was working well, but 503 errors started to happen (with the UH flag) several minutes later.
It looks like the 503 errors started to happen after a specific cds update that was applied to all the nodes but one.

There's only one main Upstream with the following configuration:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    ***
  name: ***
  namespace: ***
spec:
  circuitBreakers:
    maxConnections: 10240
    maxPendingRequests: 10240
    maxRequests: 10240
    maxRetries: 3
  failover:
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: ***
          port: 15443
          upstreamSslConfig:
            secretRef:
              name: failover-upstream
              namespace: gloo-system
            sni: ***
        locality:
          region: ***
          zone: ***
      - lbEndpoints:
        - address: ***
          port: 15443
          upstreamSslConfig:
            secretRef:
              name: failover-upstream
              namespace: gloo-system
            sni: ***
        locality:
          region: ***
          zone: ***
  healthChecks:
  - healthyThreshold: 2
    httpHealthCheck:
      path: /health/***
    interval: 2s
    timeout: 2s
    unhealthyThreshold: 2
  static:
    hosts:
    - addr: ***
      port: 80
    useTls: false
  useHttp2: false
status:
  reportedBy: gloo
  state: 1
```

After restarting all the Gloo Edge Pods again, the issue disappeared.

**To Reproduce**
The customer hasn't been able to reproduce the issue.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge 1.7.1 (rest EDS enabled)
