### ISSUE TITLE
Canary deployments with helm

### ISSUE THREAD

**Issue by antonioberben** [k8sgateway/k8sgateway#5450]
**Describe the requested changes**
For canary deployments, we do not mention which values are needed for a helm installation. We only mention the glooctl installation.

Besides, other components (i.e. prometheus) might be tied to a previous release. Once this release is deleted, its components (in this example: prometheus) it will be also deleted.

It would be interesting to be noticed in the documentation.

Currently, with default values, the installation fails due to duplicity in ClusterRoles resources in both installations (current green deployment, and new blue deployment). To mitigate the problem, a minimum set of values needs to be added. These are:

```
gloo-fed:
  enabled: false
  glooFedApiserver:
    enable: false
prometheus:
  enabled: false
```

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/master/operations/upgrading/canary/
2.
