### ISSUE TITLE
Fix validating a list of resources

### ISSUE THREAD

**Issue by MitchAman** [k8sgateway/k8sgateway#5456]
**Describe the bug**
While implementing support for lists containing upstream resources, it was discovered that kubernetes sends resources within a list to a validating admission webhook as a series of individual resources, rather than a single AdmissionReview containing the whole list of resources.  It's not clear at this point at what version the behavior stopped working, or if it ever worked.

We should either fix the list functionality for all resources, or remove it.

To reproduce:
`kubectl apply -f vs_list.yaml`

vs_list.yaml:
```
apiVersion: v1
items:
- apiVersion: gateway.solo.io/v1
  kind: VirtualService
  metadata:
    name: vs1
    namespace: gloo-system
  spec:
    virtualHost: {}
- apiVersion: gateway.solo.io/v1
  kind: VirtualService
  metadata:
    name: vs2
    namespace: gloo-system
  spec:
    virtualHost: {}
kind: List
```

Then inspect/add logging to determine if a single list was passed in, or a series of resources was received.
