### ISSUE TITLE
[UI] gloo-fed console breaks when rendering RTs that contain header matchers

### ISSUE THREAD

**Issue by lgadban** [k8sgateway/k8sgateway#5511]
**Describe the bug**
gloo-fed console breaks when rendering RTs that contain header matchers

**To Reproduce**
1. Apply VS and RT
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - delegateAction:
        selector:
          labels:
            routes: petstore
          namespaces:
          - gloo-system
      matchers:
      - prefix: /
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    routes: petstore
  name: petstore-routes
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - headers:
      - name: foo
        regex: true
        value: .*bar.*
      methods:
      - GET
      prefix: /
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system

```
3. See error
<img width="783" alt="Screen Shot 2021-10-27 at 3 18 59 PM" src="https://user-images.githubusercontent.com/1161279/139141398-4fa21552-68f8-4867-b515-feb25013746c.png">

**Expected behavior**
RT shown with no errors

**Additional context**
GlooE 1.8.15
