### ISSUE TITLE
Upstream lbEndpoints healthcheck fails with autoSniRewrite enabled

### ISSUE THREAD

**Issue by jad-solo** [k8sgateway/k8sgateway#5677]
**Describe the bug**
Upstream lbEndpoints healthcheck fails with autoSniRewrite enabled and load-balancing fails. Static definition of sni works properly.

**To Reproduce**
1. Implement upstream load-balancing to 2 tls endpoints with static sni definition: load-balancing works properly
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-bookinfo-upstream
  namespace: gloo-system
spec:
  failover:
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: endpoint2.example.com
          port: 443
          upstreamSslConfig:
            sni: endpoint2.example.com
  healthChecks:
  - healthyThreshold: 2
    httpHealthCheck:
      path: /productpage
    interval: 1s
    timeout: 1s
    unhealthyThreshold: 3
  static:
    hosts:
    - addr: endpoint1.example.com
      healthCheckConfig:
        path: /productpage
      port: 443
    useTls: true
```
2. Remove static sni definition: health-check and load-balancing fails
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-bookinfo-upstream
  namespace: gloo-system
spec:
  failover:
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: endpoint2.example.com
          port: 443
  healthChecks:
  - healthyThreshold: 2
    httpHealthCheck:
      path: /productpage
    interval: 1s
    timeout: 1s
    unhealthyThreshold: 3
  static:
    hosts:
    - addr: endpoint1.example.com
      healthCheckConfig:
        path: /productpage
      port: 443
    useTls: true
    autoSniRewrite
```

**Expected behavior**
autoSniRewrite should automatically set the sni and healthcheck/load-balancing to endpoint should work properly.

**Additional context**
- Gloo Edge version 1.8.23
- Kubernetes version 1.21.5
