### ISSUE TITLE
Add more kubeResourceOverride examples in docs

### ISSUE THREAD

**Issue by jameshbarton** [k8sgateway/k8sgateway#5711]
**Describe the requested changes**
`kubeResourceOverride` is a powerful new feature that offers a cleaner alternative to kustomize for helm customization. But users are having trouble adopting it. The only Edge docs today are in helm chart reference docs like [this](https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/).

We need some proper documentation of this feature with examples. One real-life question from an external user: How do I set `useRemoteAddress` in http connection manager settings? See more information [here](https://solo-io.slack.com/archives/C02C7U3K2HF/p1639171206061600) and [here](https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1639521283398700).

**Comment by jameshbarton** [comment]
@sam-heilbron pointed out [this doc](https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/#helm-chart-kuberesourceoverrides) to me that I must have overlooked before. I'm going to leave the ticket open. Some more complex examples would be nice, like the one mentioned in the original description. I know at least one external user and two Solo engineers who fiddled with that for hours before arriving at a solution.

**Comment by jameshbarton** [comment]
Another potential example: How to add labels for Gloo Edge pods to support distributed trace collection and categorization.

From internal support [ticket](https://solo-io.zendesk.com/agent/tickets/460):
```
gloo:
  gloo:
    deployment: 
      kubeResourceOverride:
        spec:
          template:
            metadata:
              labels:
                "edge.solo.io/cost-center": XYZ
                "edge.solo.io/project": xyz-gloo-edge
                "edge.solo.io/environment": development
```
