### ISSUE TITLE
Error from extauth passthorugh does not increase the passthrough error counter metric

### ISSUE THREAD

**Issue by antonioberben** [k8sgateway/k8sgateway#5741]
**Describe the bug**
When an error like below happens in extAuth, the releted metric (`extauth_solo_io_passthrough_check_error `) is not increased:
```
Errors encountered while processing new server configuration

1 error occurred:
	* failed to get auth service for auth config with id [pr-32734-ns.adyen-wallets-auth-adyen-wallets]; this configuration will be ignored: failed to create grpc client manager: context deadline exceeded
```

**To Reproduce**
1. Create an AuthConfig with a passthrough configuration
2. DO NOT deploy the passthrough service
3. See error in extAuth
4. The related metric `extauth_solo_io_passthrough_check_error ` seems to not be increased

**Expected behavior**
The counter metric should be increased.

**Additional context**
Add any other context about the problem here, e.g.
- The error code seems to be generated in here: https://github.com/solo-io/solo-projects/blob/6de7a2377a266669dcffa28f5f8b5876a8169c34/projects/extauth/pkg/config/generator.go#L99

Example of AuthConfig and VistualService:
```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: my-auth
  namespace: xxx
spec:
  configs:
  - passThroughAuth:
      grpc:
        address: my-passthrough-service2.svc.cluster.local:50051
  - passThroughAuth:
      grpc:
        address: my-passthrough-service1.svc.cluster.local:50051

---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: my-vs
  namespace: xxxx
spec:
  virtualHost:
    domains:
    - "*"
    options:
      extauth:
        configRef:
          name: my-auth
          namespace: xxx
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: xxx
            namespace: xxx
```
