### ISSUE TITLE
Validation webhook doesn't validate VirtualService values

### ISSUE THREAD

**Issue by csabakollar** [k8sgateway/k8sgateway#5810]
### Version

1.9.x

### Is your feature request related to a problem? Please describe.

Validation webhook doesn’t catch the following error which we accidentally run into because of a typo in our helm chart, which is responsible deploying user defined virtualservices and upstreams:

```
      ratelimit:
        rateLimits:
          - actions:
            - requestHeaders:
                descriptorKey: deviceId
```
and the headerName param is missing or empty.

### Describe the solution you'd like

The VS CRD schema (in our opinion) is missing the required  field: https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.5.3.
Or if you are using openapi v3: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L658 (edited) 

So either "fix" the CRD's schema, or implement proper value/param validation in the validation webhook service.
