### ISSUE TITLE
FailoverScheme can't be deleted if the status is FAILED

### ISSUE THREAD

**Issue by jmunozro** [k8sgateway/k8sgateway#5840]
### Gloo Edge Version

1.9.x

### Kubernetes Version

1.21.x

### Describe the bug

A FailOverScheme that is not accepted can't be deleted, because the finalizer prevents it.

### Steps to reproduce the bug

```
apiVersion: fed.solo.io/v1
kind: FailoverScheme
metadata:
  finalizers:
    - fed.solo.io/finalizer
  name: sample-backend-use1
  namespace: default
spec:
  failoverGroups:
    - priorityGroup:
        - cluster: euc1
          upstreams:
            - name: sample-backend-service
              namespace: default
  primary:
    clusterName: use1
    name: sample-backend-service
    namespace: default
status:
  message: 'failed to get client for cluster use1: Failed to get manager for cluster
    use1'
  observedGeneration: 1
  processingTime: "2022-01-28T11:18:25.958294021Z"
  state: FAILED
```

This can't be removed unless you set the finalizer as null

### Expected Behavior

Finalizer should not prevent the deletion of erroneous objects
