### ISSUE TITLE
kubeResourceOverride is not able to override elements in array

### ISSUE THREAD

**Issue by jmunozro** [k8sgateway/k8sgateway#5841]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently kubeResourceOverride is a good mechanism to customize general things, but it doesn't play well with arrays.

### Describe the solution you'd like

what i'd like:
```
gloo:
  gateway:
    validation:
      webhook:
        kubeResourceOverride:
          webhooks:
            - clientConfig:
                caBundle: mycustomvalue
```

what i have to do:
```
gloo:
  gateway:
    validation:
      webhook:
        kubeResourceOverride:
          webhooks:
            - name: gateway.gloo-system.svc
              clientConfig:
                service:
                  name: gateway
                  namespace: gloo-system
                  path: "/validation"
                caBundle: "mycustomvalue"
              rules:
              - operations: [ "CREATE", "UPDATE", "DELETE" ]
                apiGroups: ["gateway.solo.io"]
                apiVersions: ["v1"]
                resources: ["*"]
              - operations: [ "CREATE", "UPDATE", "DELETE" ]
                apiGroups: ["gloo.solo.io"]
                apiVersions: ["v1"]
                resources: ["upstreams"]
              - operations: [ "DELETE" ]
                apiGroups: ["gloo.solo.io"]
                apiVersions: ["v1"]
                resources: ["secrets"]
              sideEffects: None
              matchPolicy: Exact
              admissionReviewVersions:
                - v1beta1
              failurePolicy: Ignore
```
