### ISSUE TITLE
Custom Labels for Grafana dashboards' configmap

### ISSUE THREAD

**Issue by antonioberben** [k8sgateway/k8sgateway#5845]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

It would be interesting to allow in the helm chart to add labels to the configMap related to grafana dashboards.

So far, our customer runs its own Prometheus/Grafana. And the grafana dashboards are discovered based on a custom label.

If our chart allows custom labels, the configmap could be discovered by their grafana implementation.

### Describe the solution you'd like

Add an attribute to the chart values to allow custom labels. With in the chart, the configmap can be found at `templates/10-grafana-dashboards-config-map.yaml`

i.e:
```
grafana:
  dashboards:
    configmap:
      labels:
        # my-custom-label: my-custom-value
```
