### ISSUE TITLE
Gloo Edge Not matching any route with (#) 

### ISSUE THREAD

**Issue by asayah** [k8sgateway/k8sgateway#5877]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

Gloo Edge not matching any route created containing a (#)    ,Prefix, Exact, and Regex will not match

Same issue with envoy directly 

```
admin:
  address:
    socket_address: {address: 0.0.0.0, port_value: 9901}

static_resources:
  listeners:
  - name: listener1
    address:
      socket_address: {address: 0.0.0.0, port_value: 10000}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: demo
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: {prefix: "/alertmanager/#/status"}
                direct_response:
                  status: 200
                  body:
                    inline_string: "matched #\n"
              - match: {prefix: "/"}
                route: {cluster: demo, timeout: 60s}                
          http_filters:
          - name: envoy.filters.http.router
```

### Steps to reproduce the bug

Start envoy with this config 

### Expected Behavior

Match on #
