### ISSUE TITLE
Improve experience for adding additional gateway proxies to an existing deployment

### ISSUE THREAD

**Issue by ably77** [k8sgateway/k8sgateway#5924]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently it is possible to use Helm to deploy multiple gateway proxies, but our users would like to be able to create an additional Gateway implementation without modifying the initial Helm deployment values.yaml

Current methods to deploying an additional Gateway:
- Helm template to generate manifests for the second gateway and apply when needed
- Upgrade the default helm values.yaml with second gateway and run `helm upgrade`

Option 1 is undesirable because it would require keeping up with potential updates to helm templated resources across versions (an example here: [https://github.com/asayah/gloo-edge-team-gateway/blob/main/manifest.yaml](https://github.com/asayah/gloo-edge-team-gateway/blob/main/manifest.yaml))

Option 2 is undesirable because it requires the existing Gateways to be redefined in the updated values.yaml which is tedious and potentially error prone

A simple example:

`values-default.yaml`:
```
gloo:
  gatewayProxies:
    gatewayProxy:
      disabled: false
```

`values-added-gateway.yaml`:
```
gloo:
  gatewayProxies:
#### Adds this Gateway
    additionalGw: # Proxy name for private access (intranet facing)
      disabled: false # overwrite the "default" value in the merge step
      gatewaySettings:
        customHttpGateway: # using the default HTTP Gateway
          virtualServiceSelector:
            gateway-type: additional # label set on the VirtualService
####

#### required
    gatewayProxy:
      disabled: false
####
```

This would get unruly quickly if there were more than a few additional proxies (i.e. public + exta, public_+ extb, public + exta + extb ...)

### Describe the solution you'd like

Would like to see an approach to deploying an additional gateway that is separate from the initial deployment, so that just one gateway proxy can be deployed/configured without changes to other existing gateway proxies.

### Describe alternatives you've considered

Options listed above, but both are not ideal for reasons above

### Additional Context

Somewhat related to this issue: [https://github.com/solo-io/gloo/issues/4678](https://github.com/solo-io/gloo/issues/4678) as they are both attempting to accomplish similar goals (initial deployment + additional gateway proxies)
