### ISSUE TITLE
GraphQL value providers can not have `_` or `-` in variable names.

### ISSUE THREAD

**Issue by saiskee** [k8sgateway/k8sgateway#6065]
### Gloo Edge Version

1.11.x (beta)

### Kubernetes Version

1.21.x

### Describe the bug

```proto
message User {
  string first_name = 1;
}

service UserService {
  rpc AddUser(User) returns () {};
}
```

when the `AddUser` method is translated to a graphql schema, it defines a resolver as follows: 
```gql
     input UserInput {
        first_name: String
     }


      type Query {
        AddUser(UserSearch: UserInput): User @resolve(name: "Query|UserService.GetUser")

      }
```
and a resolver defined as 
```yaml
            grpcResolver:
              requestTransform:
                methodName: GetUser
                outgoingMessageJson:
                  username: '{$args.UserSearch.first_name}'
                serviceName: user.UserService
              upstreamRef:
                name: default-users-8080
                namespace: gloo-system
```
However, our provider template regex defined[ here](https://github.com/solo-io/solo-projects/blob/master/projects/gloo/pkg/plugins/graphql/rest_resolver.go#L226) needs to be updated to match the `first_name` underscore or else this will just be interepreted as a regular string and not an extraction template.

### Steps to reproduce the bug

na

### Expected Behavior

na
