### ISSUE TITLE
Passthrough/DontParse breaks routeAction

### ISSUE THREAD

**Issue by eafxl** [k8sgateway/k8sgateway#6158]
### Gloo Edge Version

1.10.x (latest stable)

### Describe the bug

While using the docs example with adding of passthrough/DontParse
```
  - matchers:
    - prefix: /petstore/findPets
    options:
      stagedTransformations:
        regular:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                parseBodyBehavior: DontParse
    routeAction:
      single:
        destinationSpec:
          rest:
            functionName: findPets
            parameters: {}
        upstream:
          name: petstore
          namespace: gloo-system
```
or

```
  - matchers:
    - prefix: /petstore/findPets
    options:
      stagedTransformations:
        regular:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                passthrough: {}
    routeAction:
      single:
        destinationSpec:
          rest:
            functionName: findPets
            parameters: {}
        upstream:
          name: petstore
          namespace: gloo-system
```
**path** specified in upstream yaml
```
        findPets:
          body: {}
          headers:
            :method:
              text: POST
            :path:
              text: /upload
```

become ignored, the only way to fix is to specify explicitly(in options):
```
prefixRewrite:  /upload
```

### Steps to reproduce the bug

Apply attached diff to tutorial for docker-compose (file version)

### Expected Behavior

From my perspective I should be able to not parse body and apply proper path inside upstream yml file.
