### ISSUE TITLE
Unexpected behavior of logoutPath

### ISSUE THREAD

**Issue by willowmck** [k8sgateway/k8sgateway#6179]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.21.x

### Describe the bug

I have an AuthConfig configured with OIDC and have configured the logoutPath as shown below.

```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oauth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: https://httpbin.solo.io
        callbackPath: /callback
        clientId: 166439bc-9f09-43f1-a1db-065bd14ae64c
        clientSecretRef:
          name: oauth
          namespace: gloo-system
        headers:
          idTokenHeader: jwt
        issuerUrl: http://172.18.1.2:8080/auth/realms/master/
        logoutPath: /logout
        scopes:
        - email
```

This is sitting in front of httpbin application such that when I hit the URL I am authenticated through Keycloak.  Everything looks normal for the most part when I have a default short-lived access token policy.  However, if I change the access policy expiration to be something long, like 30 minutes then it doesn't appear that `/logout` will send a backchannel request to clear the session to Keycloak.  The net result is that I can see it sending the `set-cookie` headers clearing the `id_token` and `access_token` from the client, but when I visit the app url in the browser again I am not redirected to authenticate because the session has not been cleared from Keycloak.

### Steps to reproduce the bug

You can follow the Gloo Edge workshop to setup OIDC with Keycloak and get the httpbin application running behind it.  Modify the `AuthConfig` with the setting above and setup the `access_token` expiry to 30 minutes.  Then call the `/logout` path on the app and see that the client does not get redirected to login.

### Expected Behavior

Backchannel logout should be performed on the behalf of the user, thus invalidating the session with OIDC.
