### ISSUE TITLE
Missing Gloo Metrics with ServiceMonitor

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#6311]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

The Gloo overview dashboard is missing data when using ServiceMonitors

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/65769106/163178691-8200884a-6080-4890-a277-88b7de214606.png">

### Steps to reproduce the bug

```
global:
  glooStats:
    enabled: true
    serviceMonitorEnabled: true
    serviceMonitor:
      enabled: true
      releaseLabel: kube-prometheus-stack
prometheus:
  enabled: false
grafana:
  defaultInstallationEnabled: false
observability:
  enabled: true
  customGrafana:
    enabled: true
    url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
    username: admin
    password: prom-operator
```

### Expected Behavior

Most graphs seem fine, envoy stats are coming in. I have seen the gloo dashboard with correct data occasionally.
