### ISSUE TITLE
ExtAuth - pass the UserId to the next config block

### ISSUE THREAD

**Issue by bcollard** [k8sgateway/k8sgateway#6327]
### Is your feature request related to a problem? Please describe.

GIven an AuthConfig CR with multiple config blocks
When the end-user is authenticated / when the userId is created
Put it into filter metadata so that the next item in the auth chain can read the value

Example: 
With the following AC
```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: basicauth-and-opa
  namespace: gloo-system
spec:
  configs:
  - basicAuth:
      realm: solo
      apr:
        users:
          baptiste:
            salt: u4sagt0P
            hashedPassword: 3WQ6b4Zz8zbmmRTs3rdfq1
  - opaAuth:
      modules:
      - name: parse-body
        namespace: gloo-system
      query: "data.test.allow == true"
```

I wish I can read the userId extracted by BasicAuth when the OPA rules is executed.

We already have something similar with the passthrough system, via the[ CheckRequest filterMetadata](https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/passthrough_auth/grpc/#sharing-state-with-other-auth-steps)
