### ISSUE TITLE
Grpc does not allow for similar header configuration as http_service.request

### ISSUE THREAD

**Issue by prodion23** [k8sgateway/k8sgateway#6417]
### Version

1.11 gloo-ee

### Is your feature request related to a problem? Please describe.

Hi, I'm trying to configure our existing ext_authz service to use grpc however we depend on being able to add both additional headers, send all original request headers, and send the body. 

The grpc ext_authz does not provide a similar level of capabilities as http_service(specifically in regard to headers)

```
httpService:
  request:
    allowedHeaders: []string
    headersToAdd: map<string, string> 
    allowedHeadersRegex: []string
```

  

### Describe the solution you'd like

Ideally Id like to be able to copy incoming request headers, and add additional data to be forwarded to the ext_authz service.
```
grpcService:
  request:
    headersRegex: 
    allowedHeaders:
    headersToAdd: 
```
    

### Describe alternatives you've considered

I've attempted to use the http option instead for this however, the envoy ext_autz implementation does not add grpc gateway to generate rest endpoints.
Which would enable to us to use our existing grpc ext_authz implementation over rest.
