### ISSUE TITLE
helm customEnv results in duplicate entries in deployment

### ISSUE THREAD

**Issue by pszeto** [k8sgateway/k8sgateway#6477]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

When specifying a customEnv override via helm for the extauth and rate-limit deployment.  The default environment variable and the overrides field/value are both in the resultant deployment. For example, specifying `REDIS_PASSWORD`

### Steps to reproduce the bug

1. Install 1.11.9 with the following overrides and verbose enable on the helm install command:
```
global:
  extensions:
    rateLimit:
      deployment:
        customEnv:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-test
                key: redis-password
    extAuth:
      deployment:
        customEnv:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-test
                key: redis-password
redis:
  disabled: true
  service:
    name: redis-test-master.default.svc.cluster.local
    port: 6379
```
2.  Examine the deployment for the `rate-limit` and `extauth` :

```
---
# Source: gloo-ee/templates/2-rate-limit-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: rate-limit
  name: rate-limit
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: rate-limit
  template:
    metadata:
      labels:
        gloo: rate-limit
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: rate-limit
      containers:
        - image: quay.io/solo-io/rate-limit-ee:1.11.9
          imagePullPolicy: IfNotPresent
          name: rate-limit
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GLOO_ADDRESS
              value: gloo:9977
            - name: START_STATS_SERVER
              value: "true"
            - name: REDIS_URL
              value: redis-test-master.default.svc.cluster.local:6379
            - name: REDIS_SOCKET_TYPE
              value: tcp
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: READY_PORT_HTTP
              value: "18080"
            - name: READY_PATH_HTTP
              value: "/ready"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: redis-test
          readinessProbe:
            httpGet:
              port: 18080
              path: "/ready"
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 1
      securityContext:
        runAsNonRoot: true
        runAsUser: 10101
---
# Source: gloo-ee/templates/21-extauth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: extauth
  name: extauth
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: extauth
  template:
    metadata:
      labels:
        gloo: extauth
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: extauth
      containers:
      - image: quay.io/solo-io/extauth-ee:1.11.9
        imagePullPolicy: IfNotPresent
        name: extauth
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: redis-password
                name: redis-test
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVICE_NAME
            value: "ext-auth"
          - name: GLOO_ADDRESS
            value: gloo:9977
          - name: SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: extauth-signing-key
                key: signing-key
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password
          - name: SERVER_PORT
            value: "8083"
          - name: USER_ID_HEADER
            value: "x-user-id"
          - name: START_STATS_SERVER
            value: "true"
          - name: HEALTH_HTTP_PORT
            value: "8082"
          - name: HEALTH_HTTP_PATH
            value: "/healthcheck"
        readinessProbe:
          httpGet:
            port: 8082
            path: "/healthcheck"
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
      securityContext:
        runAsNonRoot: true
        runAsUser: 10101
        fsGroup: 10101
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    gloo: gateway-proxy
                topologyKey: kubernetes.io/hostname
---
```

The deployments have two `REDIS_PASSWORD` in the `customEnv`

### Expected Behavior

The deployments for `rate-limit` and `extauth` should only have one.

### Additional Context

Because the sometimes the default 
```
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password
```
Comes after the first entry, it will take precedence.
