### ISSUE TITLE
new option to redirect on extauth failure

### ISSUE THREAD

**Issue by bcollard** [k8sgateway/k8sgateway#6568]
### Is your feature request related to a problem? Please describe.

If the extauth built-in plugins, like OIDC, AT validation, etc. return a DeniedResponse, 
we should be able to optionally send an HTTP redirect.

Today, this is only possible with the passthrough system, not with built-in plugins.

See this internal discussion: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1649676455901639

### Describe the solution you'd like

The goal is to expose a new option in the extauth settings: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#settings

similar to the existing `failureModeAllow`; something like the following:
```yaml
sendRedirectOnFailure:
  failureHttpStatus: 403 # the HTTP code returned by the extauth service
  code: 302 # the HTTP code sent to the client
  location: https://... # the URI sent to the client in the `location` header
```

### Describe alternatives you've considered

transformation on 403 response, as described in the slack thread but that doesn't look either simple or easily maintainable
