### ISSUE TITLE
Generation of Consul TLS upstreams is not working 

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#6644]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

With `settings.consulDiscovery.useTlsTagging: true`, the generated upstream does not contain the desired sslConfig. 

### Steps to reproduce the bug

1. Configure Consul with a Service and Service Instance with the `glooUseTls` tag
2. Configure settings:
```
spec:
  consul:
    address: consul-server.consul.svc.cluster.local:8500
    datacenter: dc1
    dnsAddress: 8.8.8.8:53
    serviceDiscovery:
      dataCenters:
      - dc1
  consulDiscovery:
    rootCa:
      name: httpbin-ca-cert-only
      namespace: gloo-system
    splitTlsServices: true
    tlsTagName: glooUseTls
    useTlsTagging: true
```
4. The resulting upstream looks like the following. Note there is no sslConfig and the upstream is not configured for tls:
  uid: 1b9270ce-0e35-40b2-820e-3d3286962a0d
```
spec:
  consul:
    dataCenters:
    - dc1
    serviceName: httpbin
    serviceTags:
    - glooUseTls
```

### Expected Behavior

Generated upstream is configured for TLS. The `splitTlsServices` param also seems to be broken as only one upstream is generates. 

### Additional Context

![Screen Shot 2022-06-26 at 6 30 11 AM](https://user-images.githubusercontent.com/688754/175961323-c9b8022d-9d45-4d70-b8ef-e3f0492f6f65.png)
![Screen Shot 2022-06-26 at 6 29 57 AM](https://user-images.githubusercontent.com/688754/175961332-838401a9-9f9e-422f-8ae0-bc41596920ce.png)
