### ISSUE TITLE
Matchable gateway with an empty matcher is not working

### ISSUE THREAD

**Issue by DoroNahari** [k8sgateway/k8sgateway#6646]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Matchable gateway with an empty matcher is not working since 1.11.24

Example:
```yaml
apiVersion: gateway.solo.io/v1
kind: MatchableHttpGateway
metadata:
  name: first
  namespace: test
  labels:
    hybrid-gateway: ssl
spec:
  httpGateway:
    options:
      httpConnectionManagerSettings: 
        acceptHttp10: true
    virtualServiceSelector:
      http-gateway: vs-test1
  matcher: {}
```

```yaml
apiVersion: gateway.solo.io/v1
kind: MatchableHttpGateway
metadata:
  name: second
  namespace: test
  labels:
    hybrid-gateway: ssl
spec:
  httpGateway:
    options:
      httpConnectionManagerSettings:
        acceptHttp10: false
    virtualServiceSelector:
      http-gateway: vs-test2
  matcher:
    sourcePrefixRanges:
      - addressPrefix: 10.0.0.0
        prefixLen: 16
```

```yaml
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy-ssl
  namespace: ugw-proxy
status:
  statuses:
    apigw-gloo-ee:
      reportedBy: gateway
      state: 1
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_apigw-gloo-ee':
          reportedBy: gloo
          state: 1
spec:
  bindAddress: '::'
  bindPort: 8443
  hybridGateway:
    delegatedHttpGateways:
      httpConnectionManagerSettings:
        codecType: HTTP1
        preserveCaseHeaderKeyFormat: true
        ...
      selector:
        labels:
          hybrid-gateway: ssl
      sslConfig:
        alpnProtocols:
          - http/1.1
        disableTlsSessionResumption: false
        parameters:
          cipherSuites:
            - ...
          ecdhCurves:
            - ...
  options:
    accessLoggingService: {}
    perConnectionBufferLimitBytes: 131072
  proxyNames:
    - gateway-proxy
  ssl: true
  useProxyProto: false
```

As i observed, the virtual services connected to the matchable gateway with the empty matcher didn't accept connections
The listener is not added to the gateway proxy resource.

### Steps to reproduce the bug

.

### Expected Behavior

As described in the documentation, matchable gateway with an empty matcher should accept all incoming connection.
