### ISSUE TITLE
When upstream httpProxyHostname is set then static.useTls and sslConfig: {} only apply to httpProxyHostname

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#6720]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

When upstream httpProxyHostname is set then useTls and sslConfig only apply to the target service (i.e. httpProxyHostname). There is no way to configure an ssl connection to the proxy using a non-443 port. 

### Steps to reproduce the bug

1. Configure an upstream such as this where the proxy is serving https on port 9090:
```
spec:
  httpProxyHostname: 3.94.154.124:443
  sslConfig: {}
  static:
    hosts:
    - addr: 172.31.13.225
      port: 9090
    useTls: true
```
2. That will not work as the communication to the proxy will be http. 

### Expected Behavior

There is a mechanism to configure the ssl configuration for the proxy. For example:

httpProxyHostname: 3.94.154.124:443
proxySslConfig: {}
...
