### ISSUE TITLE
Have RouteTables preserve finalizers

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#6779]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently a customer has built an operator to manage RouteTables in Gloo Edge. The lifecycle is built around finalizers and when they are set on the RT, some update by gloo removes them.

```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  annotations:
    meta.helm.sh/release-name: v1-review-andrew-37795
  creationTimestamp: '2022-07-18T20:33:33Z'
  finalizers:
    - foo
  generation: 52
  labels:
...
```

### Describe the solution you'd like

Have gloo preserve the finalizers in a RT.
