### ISSUE TITLE
Add ability to have dynamic `invalidRouteResponseBody`

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#7000]
### Version

1.11.x

### Is your feature request related to a problem? Please describe.

It would be useful to have invalid config/replaced routes return information about the route being replaced.

https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/invalid_route_replacement/

```
 gloo:
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Edge has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404
      replaceInvalidRoutes: true
```

### Describe the solution you'd like

Perhaps something like:

```
 gloo:
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Edge has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404

      replaceInvalidRoutes: true
```

### Describe alternatives you've considered

Perhaps something like:

```
 gloo:
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Edge has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404
      replaceInvalidRoutes: true
      dynamicErrorDetails: true <------
```

Then the response body could contain more details like:

`ErrorCode: 0001 - Upstream couldn't find the service` or `ErrorCode: 0002 - Invalid Route Table, no Auth configuration found`
