### ISSUE TITLE
grpc reflection not working when exposing multiple grpc services

### ISSUE THREAD

**Issue by remster** [k8sgateway/k8sgateway#7129]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.24.x

### Describe the bug

While doing basic evaluation of grpc support at Gloo, I successfully followed the tutorial on [exposing a grpc service on gloo](https://docs.solo.io/gloo-edge/master/guides/traffic_management/destination_types/grpc/), but the tutorial doesn't answer the obvious question: how to expose *two grpc services*.
The tutorial instructs to set up a VirtualService like so:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: grpc
  namespace: gloo-system
spec:
  virtualHost:
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: default-foo-9999
              namespace: gloo-system
```
and that has the `grpcurl` discover the (one) service:
```
$ grpcurl -plaintext $(glooctl proxy address --port http) list
grpc.Foo
grpc.reflection.v1alpha.ServerReflection
```
So I add the second service by adding a (same prefix) rute like so :
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: grpc
  namespace: gloo-system
spec:
  virtualHost:
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: default-foo-9999
              namespace: gloo-system
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: default-bar-9999
              namespace: gloo-system
```
but that has the `grpcurl` blind to the `bar` service
```
$ grpcurl -plaintext $(glooctl proxy address --port http) list
grpc.Foo
grpc.reflection.v1alpha.ServerReflection
```
So, inspired by how kong does it, I manipulated the prefixes like so
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: grpc
  namespace: gloo-system
spec:
  virtualHost:
    routes:
      - matchers:
-         - prefix: /
+        - prefix: /grpc.Foo
        routeAction:
          single:
            upstream:
              name: default-foo-9999
              namespace: gloo-system
      - matchers:
-         - prefix: /
+        - prefix: /grpc.Bar
        routeAction:
          single:
            upstream:
              name: default-bar-9999
              namespace: gloo-system
```
That has both grpc services exposed:
```
$ grpcurl -d '{"param": "foo"}' -plaintext -import-path ./services/bar -proto bar.proto $(glooctl proxy address --port http) grpc.Bar/Hello
{
  "param": "Hello, I am bar!\n"
}
$ grpcurl -d '{"param": "foo"}' -plaintext -import-path ./services/foo -proto foo.proto $(glooctl proxy address --port http) grpc.Foo/Hello
{
  "param": "Hello, I am foo!\n"
}
```
but the grpc server reflection ceases to work
```
$ grpcurl -plaintext $(glooctl proxy address --port http) list
Failed to list services: server does not support the reflection API
```

### Steps to reproduce the bug

Unzip the [attachment](https://github.com/solo-io/gloo/files/9542326/api-gateway.zip) and follow its the README on "Boostrap" and then "Gloo Ingress" and you should be able invoke grpc foo and bar services:

```
$ grpcurl -d '{"param": "foo"}' -plaintext -import-path ./services/bar -proto bar.proto $(glooctl proxy address --port http) grpc.Bar/Hello
{
  "param": "Hello, I am bar!\n"
}
$ grpcurl -d '{"param": "foo"}' -plaintext -import-path ./services/foo -proto foo.proto $(glooctl proxy address --port http) grpc.Foo/Hello
{
  "param": "Hello, I am foo!\n"
}
```
but unable to use the reflection
```
$ grpcurl -plaintext $(glooctl proxy address --port http) list
Failed to list services: server does not support the reflection API
```

### Expected Behavior

`grpcurl -plaintext $(glooctl proxy address --port http) list` should list both services:
```
grpc.Bar
grpc.Foo
grpc.reflection.v1alpha.ServerReflection
```
