### ISSUE TITLE
Append Extauth policy on RouteTable instead of overriding the one inherited from parent.

### ISSUE THREAD

**Issue by pszeto** [k8sgateway/k8sgateway#7329]
### Version

1.12.x (latest stable)

### Is your feature request related to a problem? Please describe.

RouteTables routeOptions configuration are inherited from parent routes, but can be overridden by the child.  There are some usecases where it it would be nice to have the ability to append an Extauth policy so that route will do the parent's extauth and then do the one defined at the route.

### Describe the solution you'd like

For example a VirtualService with an extauth policy defined:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: internal
  namespace: gloo-system
  labels:
    gateway-type: internal # label used by the "public" Gateway
spec:
  virtualHost:
    domains:
    - '*.example.corp' # listen on these public domain names
    routes:
    - matchers:
      - prefix: /
      delegateAction:
        selector:
          # 'expressions' and 'labels' cannot coexist within a single selector
          labels:
            routing-internal: top
          namespaces:
          - gloo-system
    options:
      extauth:
        configRef:
          name: global
          namespace: gloo-system 
```

A child routetable:
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    routing-internal: top
  name: internal-top-v2
  namespace: gloo-system
spec:
  weight: 10
  routes:
  - matchers:
    - prefix: /orders
    delegateAction:
      selector:
        expressions:
          - key: routing-internal
            operator: In
            values:
              - orders-valid
              - orders
        namespaces:
        - gloo-system
    options:
      extauth:
        appendExtauth: 'true'
        configRef:
          name: orders-extauth
          namespace: gloo-system            
  - matchers:
    - prefix: /prepaid
    delegateAction:
      selector:
        expressions:
          - key: routing-internal
            operator: In
            values:
              - prepaid-valid
              - prepaid
        namespaces:
        - gloo-system
  - matchers:
    - prefix: /vitamins
    delegateAction:
      selector:
        expressions:
          - key: vitamins-internal
            operator: In
            values:
              - vitamins-valid
              - vitamins
        namespaces:
        - gloo-system    
    options:
      extauth:
        appendExtauth: 'false'
        configRef:
          name: vitamins-extauth
          namespace: gloo-system       
```

In this cause, the `/orders` route will do the `global` extauth and then do the `orders-extauth`.  The `/prepaid` route will only have the `global` extauth and the `/vitamins` will override the parent's and perform only the `vitamins-extauth`
