### ISSUE TITLE
[GraphQL] - Response setter segfaults envoy on list

### ISSUE THREAD

**Issue by saiskee** [k8sgateway/k8sgateway#7378]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

GraphQlApi:
```yaml
apiVersion: graphql.gloo.solo.io/v1beta1
kind: GraphQLApi
metadata:
  name: cards-graphql
  namespace: gloo-unstable
spec:
  executableSchema:
    executor:
      local:
        enableIntrospection: true
        resolutions:
          Query|cards:
            restResolver:
              request:
                headers:
                  ':method': GET
                  ':path': /cards/api/v1/{$args.tenantId}/cards
                  Authorization: '{$headers.Authorization}'
              response:
                resultRoot: 'values[*]'
                setters:
                  type: '{$body[*].cardType}'
              upstreamRef:
                name: dbh-v1-dev-cardmanagement-8080
                namespace: gloo-unstable
    schemaDefinition: |
      
      type Card {
        type: CardType
      }

      enum CardType {
        CREDIT_CARD
        DEBIT_CARD
        VIRTUAL_CREDIT_CARD
        VIRTUAL_DEBIT_CARD
      }

      type Query {
        cards(tenantId: String): [Card!]! @resolve(name: "Query|cards")
      }
```

query `cards` segfaults envoy because of [this specific line](https://github.com/solo-io/envoy-gloo-ee/blob/master/source/extensions/graphql/resolvers/rest/rest_resolver.cc#L287). We must iterate over `new_val` instead of `response`.

### Steps to reproduce the bug

-

### Expected Behavior

-
