### ISSUE TITLE
IngressController does not take into account Gateway CRDs 

### ISSUE THREAD

**Issue by fabioaraujopt** [k8sgateway/k8sgateway#7387]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Gloo is being used as an IngressController, it is connected to an NLB via AWS ALB Controller being NLB the HTTPs termination using an ACM certificate. IngressProxy is listening on port 8080 for HTTP requests. 

All HTTPs requests are pathing trough NLB and are being routed to port 8090, as there is nothing listening on this port the NLB is showing this route as "unhealthy" and the requests are being rejected.

We tried to configure https redirection following gloo documentation using the following ingressProxy configuration (on gloo helm chart): 

```
ingressProxy:
  service:
    extraAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "external" 
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${certificate_arn}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    httpsFirst: true 
    httpPort: 80
    httpsPort: 443
    kubeResourceOverride:
      spec:
        ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 8090 # NLB listener on port 80 will redirect traffic to the Gateway listening on port 8090
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8080 # regular traffic
  deployment:
    image:
      repository: gloo-envoy-wrapper
      tag: 1.12.12
      registry: gloo
```

We also configured a gateway CRD to redirect traffic:

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy-redirect
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8090
  httpGateway:
    virtualServiceSelector:
      gloo-role: redirect-https
```

And a virtualService for it to redirect: 

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: docsmgmt-http
  namespace: gloo-system
labels: 
  gloo-role : redirect-http
spec:
  virtualHost:
    domains:
    - "*"
    routes:
    - matchers:
      - prefix: /
      redirectAction:
        hostRedirect: {OUR NLB}
        httpsRedirect: true
```

When looking into the generated CRD `ingress-proxy` we can see it ignores the gateway as well as the helm chart configuration and only have one listener (8080) and not the (8090) port.

```
apiVersion: gloo.solo.io/v1
kind: Proxy
metadata:
  labels:
    created_by: gloo-ingress
  name: ingress-proxy
  namespace: gloo-system
spec:
  listeners:
    - bindAddress: '::'
      bindPort: 8080
      httpListener:
        virtualHosts:
          XXXXX
      name: http
```

I tried to edit manually the CRD above, by adding a 8090 listener with a virtualHost configured to redirect traffic back to the NLB and it redirects the traffic. 

Although documentation explains very well how to make this setup for a gateway it does not explain for the ingressController case.

### Steps to reproduce the bug

Explained above.

### Expected Behavior

It was expected that ingressProxy would look into the gateway CRDs, or that there would exist other means to configure the proxy.
