### ISSUE TITLE
Add timestamp to status for gloo crds to indicate when it's reconciled.

### ISSUE THREAD

**Issue by pszeto** [k8sgateway/k8sgateway#7400]
### Is your feature request related to a problem? Please describe.

Sometimes when looking at VS/RT CRDs it would be nice to know when was the last time it successfully reconciled to know if translation is still happening.

### Describe the solution you'd like

Add a timestamp to status message:
```
  status:
    statuses:
      gloo-system:
        reportedBy: gloo
        state: Accepted
        updatedTime: "2022-10-28T15:53:26Z"
        subresourceStatuses:
          '*v1.Proxy.gateway-proxy_gloo-system':
            reason: "warning: \n  Route Warning: InvalidDestinationWarning. Reason:
              *v1.Upstream { gloo-system.httpbin-8000 } not found"
            reportedBy: gloo
            state: Warning
```

### Describe alternatives you've considered

An alternative would be to add the update timestamp to the metadata instead of the status.
