### ISSUE TITLE
Gateways with different matchers should not conflict on domain name

### ISSUE THREAD

**Issue by bcollard** [k8sgateway/k8sgateway#7444]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

Using `hybridGateway` with `matchedGateways`, with two matchers generates 2 filter chains in the Envoy listener with a different `filter_chain_match`. Everything is good so far.
But our controller complains that the selected VirtualServices have conflicting domain names. That should work.

### Steps to reproduce the bug

```yaml
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  hybridGateway:
    matchedGateways:
      - matcher:
          sourcePrefixRanges:
            - addressPrefix: 10.0.0.0
              prefixLen: 8
        httpGateway:
          virtualServiceSelector:
            role: blackhole
          options:
            httpConnectionManagerSettings:
              useRemoteAddress: true
      - matcher: {}
        httpGateway:
          options:
            httpConnectionManagerSettings:
              useRemoteAddress: true
            waf:
              customInterventionMessage: ModSecurity intervention! Custom message details here..
              ruleSets:
              - ruleStr: |-
                  # Turn rule engine on
                  SecRuleEngine On
                  SecRule REQUEST_HEADERS:User-Agent "scammer" "deny,status:403,id:107,phase:1,msg:'blocked scammer'"
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            clientDuration: '%DURATION%'
            httpMethod: '%REQ(:METHOD)%'
            path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            protocol: '%PROTOCOL%'
            requestId: '%REQ(X-REQUEST-ID)%'
            responseCode: '%RESPONSE_CODE%'
            responseFlags: '%RESPONSE_FLAGS%'
            systemTime: '%START_TIME%'
            targetDuration: '%RESPONSE_DURATION%'
            upstreamName: '%UPSTREAM_CLUSTER%'
            downstreamRemoteAddress: '%DOWNSTREAM_REMOTE_ADDRESS%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  ssl: false
  useProxyProto: false
```

# blackhole VS
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: blackhole
  namespace: gloo-system
  labels:
    role: blackhole
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      directResponseAction:
        status: 401
```

### Expected Behavior

no conflict
