### ISSUE TITLE
Matching sslConfigs in multiple VSs cause listener filter chain merging and loss of sniDomains config

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#7739]
### Gloo Edge Version

1.12.x

### Kubernetes Version

None

### Describe the bug

I have 2 VSs with matching sslConfig except for different `sniDomains`:

```
spec:
  sslConfig:
    oneWayTls: true
    parameters:
      cipherSuites:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-CHACHA20-POLY1305
      minimumProtocolVersion: TLSv1_2
    secretRef:
      name: server-tls-foo
      namespace: gloo-system
    sniDomains:
    - bar.com
```

```
spec:
  sslConfig:
    oneWayTls: true
    parameters:
      cipherSuites:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-CHACHA20-POLY1305
      minimumProtocolVersion: TLSv1_2
    secretRef:
      name: server-tls-foo
      namespace: gloo-system
```

**NOTE**: there is no `sniDomains` in the second VS

Have tested with `settings.gateway.isolateVirtualHostsBySslConfig: true` and `settings.gateway.isolateVirtualHostsBySslConfig: false` and the behavior is the same. 

This creates a single listener filter chain with the following. The `bar.com` server_name is lost. 

```
       "filter_chains": [
        {
         "filter_chain_match": {},
```

### Steps to reproduce the bug

1. Create 2 VSs described above
2. Note that there is only a single listener filter chain and one of the VS SNI config is lost. 

### Expected Behavior

Two listener filter chains are created preserving the `sniDomains` (or absence of)
