### ISSUE TITLE
Admin console appears to OR instead of AND for selecting RTs to display for VS

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#7870]
### Gloo Edge Version

1.12.x

### Kubernetes Version

None

### Describe the bug

RouteTables defined for a specific Virtual Service are visible under other Virtual Services in the Dashboard. Below you can see the Route Selectors for two virtual services:

```
VS: app-public
    - delegateAction:
        selector:
          expressions:
          - key: access_mode
            operator: 1
            values:
            - public
          - key: access_domain_name
            operator: 1
            values:
            - app
 
VS: api-public
    - delegateAction:
        selector:
          expressions:
          - key: access_mode
            operator: 1
            values:
            - public
          - key: access_domain_name
            operator: 1
            values:
            - api
```
 
In the dashboard I see all routes defined for the second VS also under the first one.
If I check with the glooctl everything is fine but the dashboard shows something different.

### Steps to reproduce the bug

TBD

### Expected Behavior

TBD
