### ISSUE TITLE
I need to pass specific header from gloo config to ext-auth server

### ISSUE THREAD

**Issue by anus-ali** [k8sgateway/k8sgateway#8083]
### Version

None

### Is your feature request related to a problem? Please describe.

I wanted to pass the header from gloo config to ext-auth server. 
So that I can reteive this type error from header.
I am already doing the following but not able to read header values on my ext-auth server.

```
options:
            headerManipulation:
              requestHeadersToAdd:
                - header:
                    key: type
                    value: Business
```

If it's already possible please suggest me a workaround thanks.

**Comment by afro-coder** [comment]
For adding headers before reaching ext-auth, you can use Early Transformations

The [transformations docs](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/transformations/) show the stages at which these run.

```yaml
virtualHost:
  options:
    stagedTransformations:
      regular:
        requestTransforms:
        - requestTransformation:
            transformationTemplate:
              headers:
                key:
                  text: 'Business'
```
Can you try these and let us know if it doesn't work.
