### ISSUE TITLE
Add flag to order routes in envoy based on the "best" path matcher

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8171]
### Version

1.13.x

### Is your feature request related to a problem? Please describe.

I do not want to have to manage the ordering of paths in the VirtualServices.

### Describe the solution you'd like

I would like to have Gloo create envoy config that has the paths ordered in order of most specific match to least specific path

### Describe alternatives you've considered

Manage route ordering in the VSs

**Comment by SantoDE** [comment]
*Story*
In large teams, multiple members might be working on the same `VirtualService`. In that case, Gloo Edge should have a way to specify the best patch matcher which is not depending on the order of matchers inside the actual object.
```
- apiVersion: gateway.solo.io/v1
  kind: VirtualService
  metadata:
    labels:
      app: gloo
      gloo-tier: udc-ordering
    name: order.api.dev.crndev.chick-fil-a.com
    namespace: gloo-system
  spec:
    virtualHost:
      domains:
      - api.example.com
      routes:
      - matchers:
        - prefix: /
        delegateAction:
          ref:
            name: api1
            namespace: gloo-system
      - matchers:
        - prefix: /app/
        delegateAction:
          ref:
            name: api2
            namespace: gloo-system
```

All requests would be matched by `/` regardless of the following. It should start matching from the most concrete to the less concrete and not the other way around. 

Since this might be a breaking change, we might wanna hide it behind a flag.
