### ISSUE TITLE
OpenAPI properties with _(underscore) are not represented in GraphQL schema

### ISSUE THREAD

**Issue by jackstine** [k8sgateway/k8sgateway#8181]
### Gloo Edge Version

1.13.x

### Kubernetes Version

None

### Describe the bug

the openAPI schema does not translate correctly in GraphQL schema.  The Attributes with leading `_` (`_embedded` and `_links`) fail to generate the correct GraphQL schema
```yaml
"CollectionCustomerModel": {
    "type": "object",
    "properties": {
        "_embedded": {
            "type": "object",
            "properties": {
                "customerModelList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/components/schemas/CustomerModel"
                    }
                }
            }
        },
        "_links": {
            "$ref": "#/components/schemas/Links"
        }
    }
},
```

### Steps to reproduce the bug

have an open API schema that contains leading `_` for properties. Generated GraphQL schema will not contain leading `_`. Below is a representation of the generated GraphQL.
```yaml
type CollectionCustomerModel {
  embedded: Embedded
  links: JSON
}
type Embedded {
  customerModelList: [CustomerModel]
}
type CustomerModel {
  name: String
  links: JSON
  id: Int
}
```

### Expected Behavior

Should contain `_embedded` instead of `embedded` and `_links` instead of `links`.
