### ISSUE TITLE
aerospike.tls.certSecretName must be set to empty string in 1.13.17

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#8240]
### Gloo Edge Version

1.13.x

### Kubernetes Version

1.23.x

### Describe the bug

```
Error: UPGRADE FAILED: template: gloo-ee/templates/2-rate-limit-deployment.yaml:335:4: executing "gloo-ee/templates/2-rate-limit-deployment.yaml" at <include "gloo.util.merge" (list $ctx $override "ratelimit.deploymentSpec")>: error calling include: template: gloo-ee/charts/gloo/templates/_helpers.tpl:133:22: executing "gloo.util.merge" at <include (index . 2) $top>: error calling include: template: gloo-ee/templates/2-rate-limit-deployment.yaml:219:91: executing "ratelimit.deploymentSpec" at <.Values.global.extensions.rateLimit.deployment.aerospike.tls.certSecretName>: nil pointer evaluating interface {}.certSecretName
```

the following must be added to fix the error

```
        aerospike:
          tls:
            certSecretName: ""
```

### Steps to reproduce the bug

2 values files passed during helm upgrade

```
global:
  extensions:
    rateLimit:
      deployment:
        replicas: 3
        resources:
          limits:
            cpu: 1
            memory: 256Mi
          requests:
            cpu: 1
            memory: 256Mi
```

and

```
global:
  extensions:
    rateLimit:
      deployment:
        loglevel: error
        kubeResourceOverride:
          spec:
            template:
              spec:
                priorityClassName: system-cluster-critical
```

### Expected Behavior

You should not have to define the aerospike properties
