### ISSUE TITLE
regexRewrite in redirectAction not working for request parameters

### ISSUE THREAD

**Issue by edubonifs** [k8sgateway/k8sgateway#8401]
### Version

1.14.x (latest stable)

### Is your feature request related to a problem? Please describe.

Hi, 

In Gloo Edge we are not able to make a regexRewrite in redirectAction for request parameters, as it only takes the path into consideration.

For example, I have the following redirectAction defined:
```
      options:
        regexRewrite:
          pattern:
            regex: options=(.*)
          substitution: \1
```

And I want to make the following curl:
```
curl http://url/service?options=/get
```

I would like the regex to take into consideration the ?options parameter, but it only takes into account the actual path "/service".

**Comment by SantoDE** [comment]
Current workaround - staged transformations

**Comment by edubonifs** [comment]
Hi, update to this issue, it is not enough for them to use stagedTransformation as the public URL keeps having the original request parameters, while if you do it with redirectAction the original path also changes.

It would be enough if we solve this error:

{{ request_header(\"x-origin-path\") }}: must only contain valid
            characters matching pattern ^(?:([A-Za-z0-9/:@._~!$&'()*+,:=;-]*|[%][0-9a-fA-F]{2}))*$.

If we would be able to make templates in redirectAction, as for example:
```
      stagedTransformations:
        early:
          requestTransforms:
          - clearRouteCache: true
            requestTransformation:
              transformationTemplate:
                extractors:
                  origin:
                    header: :path
                    regex: .*origin=(.*)
                    subgroup: 1
                headers:
                  x-origin-path:
                    text: '{{ origin }}'
    redirectAction:
      pathRedirect: '{{ request_header("x-origin-path") }}'
```

We would be able to make the regex in stagedTransformation and set the value of the path in the redirectAction, so we would solve the issue of regex to requestParameters in redirectActions
