### ISSUE TITLE
How to add default configurations for upstreams discovered from Consul

### ISSUE THREAD

**Issue by jasonz3157** [k8sgateway/k8sgateway#8437]
### Version

1.14.8

### Is your feature request related to a problem? Please describe.

```yaml
metadata:
  name: default
  namespace: gloo-system
gloo:
  xdsBindAddr: 0.0.0.0:9977
consul:
  httpAddress: consul-svc.default.svc.cluster.local:8500
  serviceDiscovery: {}
consulKvSource: {}
discoveryNamespace: gloo-system
refreshRate: 5s
```
When I enable automatic discovery of Consul services and Consul key-value storage, Gloo will create a new upstream in Consul's `gloo/gloo.solo.io/v1/Upstream/gloo-system/`, like:
<img src="https://github.com/solo-io/gloo/assets/48433202/ff3c54a1-77ea-4529-95eb-7c7e2ce83888" width=50%>

If I want to configure [slow_start](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/load_balancer.proto.sk/#slowstartconfig), I need to add these configurations manually :
<img src="https://github.com/solo-io/gloo/assets/48433202/e63baf5f-6834-458d-8434-e07f5df86820" width=50%>

But if the Consul service was deregistered, all these configurations in kv will also be deleted. 

After the service reappears, the upstream goes back to the initial state without my slow_start configurations.

### Describe the solution you'd like

So is there a configuration to add some default configurations for auto-discovered upstreams? 

I tried [Global annotations for upstreams](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/discovered_upstream/discovered-upstream-configuration/#global-annotations-for-upstreams), but it doesn't seem to be working.
```yaml
...
consul:
  httpAddress: consul-svc.default.svc.cluster.local:8500
  serviceDiscovery: {}
consulKvSource: {}
upstreamOptions:
  globalAnnotations:
    gloo.solo.io/upstream_config: '{"loadBalancerConfig":{"roundRobin":{"slowStartConfig":{"slowStartWindow":"60s"}}}}'
```
