### ISSUE TITLE
Prefix rewrite for specific upstream

### ISSUE THREAD

**Issue by codepawpaw** [k8sgateway/k8sgateway#8501]
### Version

None

### Is your feature request related to a problem? Please describe.

Hi fellas
Is it possible to enable prefix rewrite for specific upstream
Let me give the illustration with code snippet bellow
```
        multi:
          destinations:
            - weight: {{ .Values.virtualService.weightVm }}
              destination:
                upstream:
                  name: foo-vm
                  namespace: foo
            - weight: {{ .Values.virtualService.weightGke }}
              destination:
                upstream:
                  name: foo-foo-primaryupstream-80
                  namespace: foo
                  options:
                    prefixRewrite: '/public/'
      options:
        timeout: '60s'
```
          
I expect the request prefix gonna be change to be /public after distribute to foo-foo-primaryupstream-80

### Describe the solution you'd like

I have no idea how complex its
But i think it will be better if we can have options for each upstream destinations
