### ISSUE TITLE
Support GlooFed on Azure

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8503]
### Version

None

### Is your feature request related to a problem? Please describe.

We are using Gloo-Fed to provide an UI to our product teams. Gloo-Fed at the moment is only able to use Kubeconfig to authenticate to remote K8S clusters and to get the info from the remote Gloo-Edge clusters.
Due to a recent change, we did change a bit our Kubeconfig on Azure by adding a custom exec command:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: ...
  name: azure-sandbox-kubernetes-vmss
contexts:
- context:
    ...
current-context: azure-sandbox-kubernetes-vmss
kind: Config
users:
- name: clusterUser_kubernetes-vmss_azure-sandbox-kubernetes-vmss
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
       ...
      command: kubelogin <====== custom command
      env: null
      provideClusterInfo: false
```
We tried to pass the new Kubeconfig to Gloo-Fed but then Gloo-Fed is not able to execute the kubelogin  command of course as it is not installed inside the container. Resulting in Gloo-Fed not being able to get info from Gloo-Edge on Azure clusters.

### Describe the solution you'd like

Support GlooFed Azure auth described above
