### ISSUE TITLE
RateLimitConfig with duplicate descriptors causes flood of errors from rate-limit server

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8620]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.13.x

### Kubernetes Version

1.24

### Describe the bug

A RLC with duplicate descriptors causes the rate-limit server to constantly throw this error:

`{"level":"error","ts":"2023-08-24T16:54:19.841Z","caller":"xds/module.go:101","msg":"failed to generate configuration for domain","version":"1.13.19","domain":"crd","error":"1 error occurred:\n\t* Error loading new tree descriptors: duplicate descriptor composite key [crd|generic_key^gloo-system.generic|generic_key^count]\n\n","stacktrace":"github.com/solo-io/solo-projects/projects/rate-limit/pkg/xds.(*configSource).Run.func1.1\n\t/go/src/github.com/solo-io/solo-projects/projects/rate-limit/pkg/xds/module.go:101\ngithub.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise.applyRateLimitConfig.func1\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.13.20/projects/gloo/pkg/api/v1/enterprise/rate_limit_discovery_service_xds.sk.go:111\ngithub.com/solo-io/solo-kit/pkg/api/v1/control-plane/client.(*client).Start\n\t/go/pkg/mod/github.com/solo-io/solo-kit@v0.30.9/pkg/api/v1/control-plane/client/client.go:137\ngithub.com/solo-io/solo-projects/projects/rate-limit/pkg/xds.(*configSource).Run.func1\n\t/go/src/github.com/solo-io/solo-projects/projects/rate-limit/pkg/xds/module.go:126\ngithub.com/solo-io/go-utils/contextutils.(*exponentialBackoff).Backoff\n\t/go/pkg/mod/github.com/solo-io/go-utils@v0.23.0/contextutils/backoff.go:70\ngithub.com/solo-io/solo-projects/projects/rate-limit/pkg/xds.(*configSource).Run\n\t/go/src/github.com/solo-io/solo-projects/projects/rate-limit/pkg/xds/module.go:129\ngithub.com/solo-io/rate-limiter/pkg/server.Server.Start.func2\n\t/go/pkg/mod/github.com/solo-io/rate-limiter@v0.7.11/pkg/server/server.go:124"}`

### Expected Behavior

Duplicate is ignored with a warning, does not flood the logs with errors. 

### Steps to reproduce the bug

```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: generic
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 1
        unit: MINUTE
      value: count
    - key: generic_key
      rateLimit:
        requestsPerUnit: 1
        unit: MINUTE
      value: count
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: count
```

VirtualService snippet:

```
    - matchers:
      - prefix: /ratelimitenvoy/
      name: ratelimitenvoy
      options:
        prefixRewrite: /
        rateLimitConfigs:
          refs:
          - name: generic
            namespace: gloo-system
        waf:
          disabled: true
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
```
