### ISSUE TITLE
Route with routeAction.dynamicForwardProxy breaks tunneling proxy config

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8641]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.13.x

### Kubernetes Version

1.24

### Describe the bug

If I deploy a route with routeAction.dynamicForwardProxy then another route referencing an http tunneling proxy upstream results in the tunneling config not being generated

### Expected Behavior

route referencing an http tunneling proxy upstream the tunneling config are not impacted by other routes and are properly configured for tunneling 

### Steps to reproduce the bug

1. Deploy attached min-vs.yaml. Note that the tunneling config is generated in envoy. 
2. Deploy attached brokentunnel-vs.yaml. Note the tunneling config is not generated in envoy

[vs.tar.gz](https://github.com/solo-io/gloo/files/12501833/vs.tar.gz)

**Comment by bdecoste** [comment]
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: connect
  namespace: gloo-system
spec:
  httpProxyHostname: httpbin.org:80
  static:
    hosts:
    - addr: goproxy.gloo-system.svc.cluster.local
      port: 8080
    useTls: false
```
