### ISSUE TITLE
Expose log level configuration for all gloo-fed containers

### ISSUE THREAD

**Issue by huzlak** [k8sgateway/k8sgateway#8734]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.14.8

### Is your feature request related to a problem? Please describe.

I 'd like to be able to declaratively set log level for gloo-fed components. 

### Describe the solution you'd like

Helm chart option as we do for other gloo components:

```
gloo-fed:
  enabled: true
  glooFed:
    logLevel: warn
  glooFedApiserver:
    enable: true
    logLevel: warn
```

### Describe alternatives you've considered

Using `customEnv` [chart option](https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/#:~:text=gloo%2Dfed.glooFed.customEnv%5B%5D.name) to set env variables, but it's ignored.
