### ISSUE TITLE
Expose statusOnError under global.extensions.extauth in the helm chart

### ISSUE THREAD

**Issue by edubonifs** [k8sgateway/k8sgateway#8802]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

This feature request is for exposing statusOnError under global.extensions.extauth in the helm chart

```
global:
  extensions:
    extAuth:
      statusOnError: 401
```
