### ISSUE TITLE
Add additional logic to pathRedirect regex

### ISSUE THREAD

**Issue by edubonifs** [k8sgateway/k8sgateway#8812]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.15.x

### Kubernetes Version

1.26

### Describe the bug

There are some URLs that are valid but the logic implemented with current regex is not able to recognize it as valid.
This is the current regex that we are using: ^(?:([A-Za-z0-9/:@._~!$&'()*+,:=;-]*|[%][0-9a-fA-F]{2}))*$

However, there are some valid URLs as the following one:
```
/realms/keycloak/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2keycloak.test.us-east-1.aws.keycloak.io%2Foidc-logout
```

The regex doesn't behave good when "?" is added to the URL

### Expected Behavior

It should be able to recognize the above URL as valid, as it is a valid URL, maybe adding "?" to the regex would fix the issue.
^(?:([A-Za-z0-9/:@._~!$&'()*+?,:=;-]*|[%][0-9a-fA-F]{2}))*$

Or maybe there is some reason we don't want this paths to be accepted

### Steps to reproduce the bug

Create a VirtualService with the following spec: 
```
spec:
  routes:
    - matchers:
        - prefix: /logout
      redirectAction:
        hostRedirect: idp.dev.us-east-2.aws.tkcloud.io
        pathRedirect: /realms/prodigy/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fannot01.dev.us-east-2.aws.tkcloud.io%2Foidc-logout
```
