### ISSUE TITLE
`slowStartConfig` 

### ISSUE THREAD

**Issue by totallyGreg** [k8sgateway/k8sgateway#8920]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.14.6

### Kubernetes Version

v1.2.x

### Describe the bug

Setting `slowStartConfig` results in error:
```
  loadBalancerConfig:
    roundRobin:
      slowStartConfig:
        aggression: 1
        minWeightPercent: 10
        slowStartWindow: 30s
```

```
[2023-11-14 17:20:47.785][7][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.cluster.v3.Cluster rejected: Proto constraint validation failed (ClusterValidationError.RoundRobinLbConfig: embedded message failed validation | caused by RoundRobinLbConfigValidationError.SlowStartConfig: embedded message failed validation | caused by SlowStartConfigValidationError.Aggression: embedded message failed validation | caused by RuntimeDoubleValidationError.RuntimeKey: value length must be at least 1 characters): name: "frontendservice-host-us_testing1234"
```

When setting the `slowStartConfig` option, the aggression value is being set as `default_value`, but missing the `runtime_key` which is required. 

```
round_robin_lb_config {
  slow_start_config {
    slow_start_window {
      seconds: 30
    }
    aggression {
      default_value: 1
    }
    min_weight_percent {
      value: 10
    }
  }
}
```
 See.  https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#config-core-v3-runtimedouble

### Expected Behavior

`slowStartConfig` feature should work by generating valid envoy config.  

### Steps to reproduce the bug

Apply `loadBalancerConfig` with `slowStartConfig` option configured

```
  loadBalancerConfig:
    roundRobin:
      slowStartConfig:
        aggression: 1
        minWeightPercent: 10
        slowStartWindow: 30s
```
