### ISSUE TITLE
With Istio enabled, session affinity aware routing does not work anymore

### ISSUE THREAD

**Issue by ncabanis** [k8sgateway/k8sgateway#9085]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.15.18

### Kubernetes Version

OpenShift 4.14.5

### Describe the bug

We are using the lbHash mechanism with cookies for implementing sticky sessions. Like this:
```
kind: VirtualService
spec:
  virtualHost:
    ...
    routes:
    - matchers:
      - prefix: /
      options:
        lbHash:
          hashPolicies:
          - cookie:
              name: session-id
```

For example:
`curl -v -H "Cookie: session-id=ASDASDASD" app1.team-rp-test.apps.stgv2.clusters.adcubum.com/hostname`
will result routing to the same pod each time.

If we activate Istio now:
```
gloo:
  global:
    istioIntegration:
      disableAutoinjection: true
      enableIstioSidecarOnGateway: true
      labelInstallNamespace: false
      whitelistDiscovery: false
    istioSDS:
      enabled: true
```
the sticky session routing does not work anymore.

When comparing the Envoy config, the following difference strikes the eye.

With Istio enabled, endpoint is a service IP:
```
    "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "app1-67746fd7d8_team-rp-test-9347995334432883430",
      "endpoints": [
        {
          "lb_endpoints": [
            {
              "endpoint": {
                "address": {
                  "socket_address": {
                    "address": "172.30.216.185",
                    "port_value": 8080
                  }
                },
                "health_check_config": {}
              },
```

Without Istio, endpoints are a list of pod IPs:
```
    "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "app1-67746fd7d8_team-rp-test-8249188866021865606",
      "endpoints": [
        {
          "lb_endpoints": [
            {
              "endpoint": {
                "address": {
                  "socket_address": {
                    "address": "10.129.4.127",
                    "port_value": 8080
                  }
                },
                "health_check_config": {}
              },
              "health_status": "HEALTHY",
              "load_balancing_weight": 1,
...
              }
            },
            {
              "endpoint": {
                "address": {
                  "socket_address": {
                    "address": "10.130.3.174",
                    "port_value": 8080
                  }
                },
                "health_check_config": {}
              },
              "health_status": "HEALTHY",
              "load_balancing_weight": 1,
...
              }
            },
            {
              "endpoint": {
                "address": {
                  "socket_address": {
                    "address": "10.130.6.197",
                    "port_value": 8080
                  }
                },
                "health_check_config": {}
              },
```

### Expected Behavior

The sticky session load-balancing should also work with Istio enabled.

### Steps to reproduce the bug

This script does not match the config dump extracts from above, but still should be easy to follow.
[Session-Affinity-reproducer.md](https://github.com/solo-io/gloo/files/14011784/Session-Affinity-reproducer.md)
